eureka:
    client:
        register-with-eureka: false

server:
  port: 8080

spring:

  application:
    name: msvc-gateway
  cloud:
    gateway:
      discovery:
        locator:
          enabled: true
      routes:
        - id: user
          uri: http://localhost:8090
          predicates:
            - Path=/api/user/**
        - id: rutas
          uri: http://localhost:9090
          predicates:
            - Path=/api/rutas/**
