spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/userDB
    username: alfredo
    password: notebok456
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: create
    show-sql: true
    database-platform: org.hibernate.dialect.PostgreSQLDialect
eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/
